# Generated by Django 6.0.1 on 2026-02-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_branch_user_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="title",
            field=models.CharField(blank=True, default="No Title", max_length=200),
        ),
    ]
