# Generated by Django 6.0.1 on 2026-02-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_complaint_priority_complaint_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
