# Generated by Django 6.0.1 on 2026-02-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_complaint_image_departmentpointtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentpointtransaction",
            name="penalty_day",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
