# Generated by Django 6.0.1 on 2026-02-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_departmentpointtransaction_penalty_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="priority",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
    ]
