# Generated by Django 6.0.1 on 2026-02-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_complaint_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roll_no",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
