# Generated by Django 6.0.1 on 2026-02-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_user_roll_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="college_name",
            field=models.CharField(
                blank=True, default="Not Mentioned", max_length=100, null=True
            ),
        ),
    ]
