# Generated by Django 6.0.1 on 2026-02-13 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_user_college_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="college_name",
        ),
        migrations.AddField(
            model_name="department",
            name="college",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.college",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.college",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("college", "name")},
        ),
    ]
