# Generated by Django 6.0.1 on 2026-02-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_college_remove_user_college_name_department_college_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
    ]
