# Generated by Django 6.0.1 on 2026-02-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_complaint_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="branch",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="Branch",
        ),
    ]
