# Generated by Django 6.0.1 on 2026-02-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="complaints"),
        ),
    ]
