# Generated by Django 6.0.1 on 2026-02-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_complaint_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
