# Generated by Django 6.0.1 on 2026-02-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_department_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("college", "name")},
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="roll_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("college", "code"), ("college", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("college", "roll_no"), ("college", "username")},
        ),
    ]
