# Generated by Django 6.0.1 on 2026-02-14 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_department_user_alter_user_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
