# Generated by Django 6.0.1 on 2026-02-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_user_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="similarity_hash",
            field=models.TextField(blank=True, null=True),
        ),
    ]
