# Generated by Django 6.0.1 on 2026-02-14 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_complaint_similarity_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="times_reported",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="departmentpointtransaction",
            name="complaint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.complaint",
            ),
        ),
    ]
