# Generated by Django 6.0.1 on 2026-02-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_complaint_times_reported_department_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="repeated_complaint",
            field=models.BooleanField(default=False),
        ),
    ]
