# Generated by Django 6.0.1 on 2026-02-15 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_complaint_repeated_complaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="college",
            field=models.ForeignKey(
                default=None,
                null=True,
                blank=True,
                related_name="complaints",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.college",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="college",
            field=models.ForeignKey(
                default=None,
                null=True,
                blank=True,
                related_name="departments",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.college",
            ),
        ),
    ]
