# Generated by Django 6.0.1 on 2026-02-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_complaint_college_alter_department_college"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="times_reported",
            field=models.FloatField(default=1),
        ),
    ]
