# Generated by Django 6.0.1 on 2026-02-15 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_complaint_times_reported"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentpointtransaction",
            name="complaint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.complaint",
            ),
        ),
    ]
