# Generated by Django 6.0.1 on 2026-02-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_departmentpointtransaction_complaint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending (AI Assigned)"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                    ("REMOVED", "Removed by Student"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
