# Generated by Django 6.0.1 on 2026-02-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_department_no_of_complaints_resolved_alertmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertmessage",
            name="asstimated_resolve_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
