# Generated by Django 6.0.1 on 2026-02-16 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alertmessage_asstimated_resolve_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="no_of_complaints_resolved",
            new_name="no_of_complaints",
        ),
    ]
