# Generated by Django 6.0.1 on 2026-02-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_rename_no_of_complaints_resolved_department_no_of_complaints"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alertmessage",
            old_name="asstimated_resolve_time",
            new_name="estimated_resolution_time",
        ),
    ]
