# Generated by Django 6.0.1 on 2026-02-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0033_rename_asstimated_resolve_time_alertmessage_estimated_resolution_time",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertmessage",
            name="estimated_resolution_time",
        ),
        migrations.AddField(
            model_name="alertmessage",
            name="resolution_days",
            field=models.IntegerField(
                default=0, help_text="Number of days until resolution"
            ),
        ),
        migrations.AddField(
            model_name="alertmessage",
            name="resolution_hours",
            field=models.IntegerField(default=0, help_text="Additional hours (0-23)"),
        ),
    ]
