# Generated by Django 6.0.1 on 2026-02-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_remove_alertmessage_estimated_resolution_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="resolved_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="complaints/resolved"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="feedback"),
        ),
    ]
